(defpackage bullet-physics
  (:use :cl :alexandria)
  (:nicknames bullet)
  (:documentation 
   
   "Bullet is a Collision Detection and Rigid Body Dynamics Library.
 The Library is Open Source and free for commercial use, under the
 zlib.  The C++ documentation is at bulletphysics.org; this is a
 simple wrapper to make Bullet available to Common Lisp programs.

This package was hand-edited to save time over learning
Swig properly.")
  (:export 
   #:*disable-deactivation*
   #:*infinity-mask*
   #:*overlapping-pairs*
   #:*s-bullet-dnalen*
   #:*s-bullet-dnalen-64*
   #:*s-bullet-dnastr*
   #:*s-bullet-dnastr-64*
   #:+-bt-use-center-limit-+
   #:+6-dof-flags-axis-shift+
   #:+active-tag+
   #:+bullet-version+
   #:+collision-object-data-name+
   #:+collision-object-data-name+
   #:+cone-twist-constraint-data-name+
   #:+dbvt-bp-accuratesleeping+
   #:+dbvt-bp-enable-benchmark+
   #:+dbvt-bp-preventfalseupdate+
   #:+dbvt-bp-profile+
   #:+disable-deactivation+
   #:+disable-deactivation+
   #:+disable-simulation+
   #:+disable-simulation+
   #:+dynamic-set+
   #:+fixed-set+
   #:+gear-constraint-data-name+
   #:+generic-6-dof-constraint-data-name+
   #:+generic-6-dof-spring-constraint-data-name+
   #:+header-length+
   #:+hinge-constraint-data-name+
   #:+island-sleeping+
   #:+island-sleeping+
   #:+large-float+
   #:+point-2-point-constraint-data-name+
   #:+rigid-body-data-name+
   #:+slider-constraint-data-name+
   #:+stagecount+
   #:+typed-constraint-data-name+
   #:+use-bt-clock+
   #:+use-dispatch-registry-array+
   #:+use-overlap-test-on-removes+
   #:+use-placement-new+
   #:+vector-3-data-name+
   #:+wants-deactivation+
   #:+wants-deactivation+
   #:6-dof-flags
   #:6-dof-flags
   #:6dof-data
   #:aabb-test
   #:activate
   #:activation-state
   #:activation-state-1
   #:activation-state-1
   #:activep
   #:add-action
   #:add-character
   #:add-collision-object
   #:add-constraint
   #:add-rigid-body
   #:add-single-result
   #:add-vehicle
   #:additional-angular-damping-factor
   #:additional-angular-damping-threshold-sqr
   #:additional-damping
   #:additional-damping-factor
   #:additional-linear-damping-threshold-sqr
   #:adjust-angle-to-limits
   #:aligned-alloc-internal
   #:aligned-alloc-set-custom
   #:aligned-alloc-set-custom-aligned
   #:aligned-free-internal
   #:all-hits-ray-result-callback
   #:angle
   #:angular-damping
   #:angular-factor
   #:angular-limit/fit
   #:angular-limit/get-bias-factor
   #:angular-limit/get-correction
   #:angular-limit/get-error
   #:angular-limit/get-half-range
   #:angular-limit/get-high
   #:angular-limit/get-low
   #:angular-limit/get-relaxation-factor
   #:angular-limit/get-sign
   #:angular-limit/get-softness
   #:angular-limit/is-limit
   #:angular-limit/set
   #:angular-limit/test
   #:angular-lower-limit
   #:angular-only
   #:angular-sleeping-threshold
   #:angular-upper-limit
   #:angular-velocity
   #:anisotropic-friction
   #:anisotropic-friction
   #:anisotropic-friction-flags
   #:anisotropic-friction-flags
   #:applied-force-body-a
   #:applied-force-body-b
   #:applied-impulse
   #:applied-torque-body-a
   #:applied-torque-body-b
   #:apply-gravity
   #:apply-speculative-contact-restitution
   #:arc-cosine
   #:arc-sine
   #:arc-tangent
   #:atan-2
   #:atan-2-fast
   #:axis-in-a
   #:axis-in-b
   #:basis
   #:benchmark
   #:bias-factor
   #:box-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:box-shape/calculate-local-inertia
   #:box-shape/delete-c++-array
   #:box-shape/delete-c++-instance
   #:box-shape/get-aabb
   #:box-shape/get-edge
   #:box-shape/get-half-extents-with-margin
   #:box-shape/get-half-extents-without-margin
   #:box-shape/get-name
   #:box-shape/get-num-edges
   #:box-shape/get-num-planes
   #:box-shape/get-num-preferred-penetration-directions
   #:box-shape/get-num-vertices
   #:box-shape/get-plane
   #:box-shape/get-plane-equation
   #:box-shape/get-preferred-penetration-direction
   #:box-shape/get-vertex
   #:box-shape/is-inside
   #:box-shape/local-get-supporting-vertex
   #:box-shape/local-get-supporting-vertex-without-margin
   #:box-shape/make-c++-array
   #:box-shape/make-c++-instance
   #:box-shape/set-local-scaling
   #:box-shape/set-margin
   #:breaking-impulse-threshold
   #:broadphase
   #:broadphase-handle
   #:broadphase-handle
   #:bu/simplex-1to-4/add-vertex
   #:bu/simplex-1to-4/delete-c++-array
   #:bu/simplex-1to-4/delete-c++-instance
   #:bu/simplex-1to-4/get-aabb
   #:bu/simplex-1to-4/get-edge
   #:bu/simplex-1to-4/get-index
   #:bu/simplex-1to-4/get-name
   #:bu/simplex-1to-4/get-num-edges
   #:bu/simplex-1to-4/get-num-planes
   #:bu/simplex-1to-4/get-num-vertices
   #:bu/simplex-1to-4/get-plane
   #:bu/simplex-1to-4/get-vertex
   #:bu/simplex-1to-4/is-inside
   #:bu/simplex-1to-4/make-c++-array
   #:bu/simplex-1to-4/make-c++-instance
   #:bu/simplex-1to-4/reset
   #:bullet/optimize
   #:bullet/ratio
   #:bullet> 
   #:bvh-triangle-mesh-shape/build-optimized-bvh
   #:bvh-triangle-mesh-shape/calculate-serialize-buffer-size
   #:bvh-triangle-mesh-shape/delete-c++-array
   #:bvh-triangle-mesh-shape/delete-c++-instance
   #:bvh-triangle-mesh-shape/get-name
   #:bvh-triangle-mesh-shape/get-optimized-bvh
   #:bvh-triangle-mesh-shape/get-owns-bvh
   #:bvh-triangle-mesh-shape/get-triangle-info-map
   #:bvh-triangle-mesh-shape/make-c++-array
   #:bvh-triangle-mesh-shape/make-c++-instance
   #:bvh-triangle-mesh-shape/partial-refit-tree
   #:bvh-triangle-mesh-shape/perform-convexcast
   #:bvh-triangle-mesh-shape/perform-raycast
   #:bvh-triangle-mesh-shape/process-all-triangles
   #:bvh-triangle-mesh-shape/refit-tree
   #:bvh-triangle-mesh-shape/serialize
   #:bvh-triangle-mesh-shape/serialize-single-bvh
   #:bvh-triangle-mesh-shape/serialize-single-triangle-info-map
   #:bvh-triangle-mesh-shape/set-local-scaling
   #:bvh-triangle-mesh-shape/set-optimized-bvh
   #:bvh-triangle-mesh-shape/set-triangle-info-map
   #:bvh-triangle-mesh-shape/uses-quantized-aabb-compression
   #:calculate-overlapping-pairs
   #:calculate-serialize-buffer-size
   #:capsule-shape-data
   #:capsule-shape-x/get-name
   #:capsule-shape-z/get-name
   #:capsule-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:capsule-shape/calculate-local-inertia
   #:capsule-shape/calculate-serialize-buffer-size
   #:capsule-shape/delete-c++-array
   #:capsule-shape/delete-c++-instance
   #:capsule-shape/get-aabb
   #:capsule-shape/get-anisotropic-rolling-friction-direction
   #:capsule-shape/get-half-height
   #:capsule-shape/get-name
   #:capsule-shape/get-radius
   #:capsule-shape/get-up-axis
   #:capsule-shape/local-get-supporting-vertex-without-margin
   #:capsule-shape/make-c++-array
   #:capsule-shape/make-c++-instance
   #:capsule-shape/serialize
   #:capsule-shape/set-local-scaling
   #:capsule-shape/set-margin
   #:ccd-motion-threshold
   #:ccd-motion-threshold
   #:ccd-square-motion-threshold
   #:ccd-swept-sphere-radius
   #:ccd-swept-sphere-radius
   #:center-of-mass-offset
   #:check-collide-with
   #:check-collide-with
   #:child-margin
   #:child-shape
   #:child-shape-ptr
   #:child-shape-type
   #:chunk/m/chunk-code/get
   #:chunk/m/chunk-code/set
   #:chunk/m/dna/nr/get
   #:chunk/m/dna/nr/set
   #:chunk/m/length/get
   #:chunk/m/length/set
   #:chunk/m/number/get
   #:chunk/m/number/set
   #:chunk/m/old-ptr/get
   #:chunk/m/old-ptr/set
   #:cid
   #:clear-forces
   #:clock/assign-value
   #:clock/get-time-microseconds
   #:clock/get-time-milliseconds
   #:clock/reset
   #:closest-convex-result-callback
   #:closest-hit-fraction
   #:closest-ray-result-callback
   #:collide
   #:collision-algorithm-pool
   #:collision-dispatcher/allocate-collision-algorithm
   #:collision-dispatcher/clear-manifold
   #:collision-dispatcher/default-near-callback
   #:collision-dispatcher/dispatch-all-collision-pairs
   #:collision-dispatcher/find-algorithm
   #:collision-dispatcher/free-collision-algorithm
   #:collision-dispatcher/get-collision-configuration
   #:collision-dispatcher/get-dispatcher-flags
   #:collision-dispatcher/get-internal-manifold-pointer
   #:collision-dispatcher/get-internal-manifold-pool
   #:collision-dispatcher/get-manifold-by-index-internal
   #:collision-dispatcher/get-near-callback
   #:collision-dispatcher/get-new-manifold
   #:collision-dispatcher/get-num-manifolds
   #:collision-dispatcher/needs-collision
   #:collision-dispatcher/needs-response
   #:collision-dispatcher/register-collision-create-func
   #:collision-dispatcher/release-manifold
   #:collision-dispatcher/set-collision-configuration
   #:collision-dispatcher/set-dispatcher-flags
   #:collision-dispatcher/set-near-callback
   #:collision-filter-group
   #:collision-filter-mask
   #:collision-flags
   #:collision-flags
   #:collision-margin
   #:collision-object
   #:collision-object-array
   #:collision-object-data
   #:collision-object-double-data
   #:collision-object-float-data
   #:collision-object-float-data
   #:collision-object-types
   #:collision-object-types
   #:collision-object/delete-c++-array
   #:collision-object/delete-c++-instance
   #:collision-object/make-c++-array
   #:collision-object/make-c++-instance
   #:collision-objects
   #:collision-shape
   #:collision-shape
   #:collision-shape-data
   #:collision-world
   #:collision-world/add-collision-object
   #:collision-world/compute-overlapping-pairs
   #:collision-world/contact-pair-test
   #:collision-world/contact-test
   #:collision-world/convex-sweep-test
   #:collision-world/debug-draw-object
   #:collision-world/debug-draw-world
   #:collision-world/get-broadphase
   #:collision-world/get-collision-object-array
   #:collision-world/get-debug-drawer
   #:collision-world/get-dispatch-info
   #:collision-world/get-dispatcher
   #:collision-world/get-force-update-all-aabbs
   #:collision-world/get-num-collision-objects
   #:collision-world/get-pair-cache
   #:collision-world/object-query-single
   #:collision-world/object-query-single-internal
   #:collision-world/perform-discrete-collision-detection
   #:collision-world/ray-test
   #:collision-world/ray-test-single
   #:collision-world/ray-test-single-internal
   #:collision-world/remove-collision-object
   #:collision-world/serialize
   #:collision-world/set-broadphase
   #:collision-world/set-debug-drawer
   #:collision-world/set-force-update-all-aabbs
   #:collision-world/update-aabbs
   #:collision-world/update-single-aabb
   #:companion-id
   #:companion-id
   #:compound-shape-child
   #:compound-shape-child-data
   #:compound-shape-data
   #:compound-shape/add-child-shape
   #:compound-shape/calculate-local-inertia
   #:compound-shape/calculate-principal-axis-transform
   #:compound-shape/calculate-serialize-buffer-size
   #:compound-shape/create-aabb-tree-from-children
   #:compound-shape/delete-c++-array
   #:compound-shape/delete-c++-instance
   #:compound-shape/get-aabb
   #:compound-shape/get-child-list
   #:compound-shape/get-child-shape
   #:compound-shape/get-child-transform
   #:compound-shape/get-dynamic-aabb-tree
   #:compound-shape/get-local-scaling
   #:compound-shape/get-margin
   #:compound-shape/get-name
   #:compound-shape/get-num-child-shapes
   #:compound-shape/get-update-revision
   #:compound-shape/make-c++-array
   #:compound-shape/make-c++-instance
   #:compound-shape/recalculate-local-aabb
   #:compound-shape/remove-child-shape
   #:compound-shape/remove-child-shape-by-index
   #:compound-shape/serialize
   #:compound-shape/set-local-scaling
   #:compound-shape/set-margin
   #:compound-shape/update-child-transform
   #:compute-overlapping-pairs
   #:cone-shape-data
   #:cone-shape-x/get-anisotropic-rolling-friction-direction
   #:cone-shape-x/get-name
   #:cone-shape-z/get-anisotropic-rolling-friction-direction
   #:cone-shape-z/get-name
   #:cone-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:cone-shape/calculate-local-inertia
   #:cone-shape/calculate-serialize-buffer-size
   #:cone-shape/delete-c++-array
   #:cone-shape/delete-c++-instance
   #:cone-shape/get-anisotropic-rolling-friction-direction
   #:cone-shape/get-cone-up-index
   #:cone-shape/get-height
   #:cone-shape/get-name
   #:cone-shape/get-radius
   #:cone-shape/local-get-supporting-vertex
   #:cone-shape/local-get-supporting-vertex-without-margin
   #:cone-shape/make-c++-array
   #:cone-shape/make-c++-instance
   #:cone-shape/serialize
   #:cone-shape/set-cone-up-index
   #:cone-shape/set-local-scaling
   #:cone-twist-constraint-data
   #:cone-twist-constraint-double-data
   #:cone-twist-constraint/build-jacobian
   #:cone-twist-constraint/calc-angle-info
   #:cone-twist-constraint/calc-angle-info-2
   #:cone-twist-constraint/calculate-serialize-buffer-size
   #:cone-twist-constraint/delete-c++-array
   #:cone-twist-constraint/delete-c++-instance
   #:cone-twist-constraint/enable-motor
   #:cone-twist-constraint/get-aframe
   #:cone-twist-constraint/get-bframe
   #:cone-twist-constraint/get-fix-thresh
   #:cone-twist-constraint/get-frame-offset-a
   #:cone-twist-constraint/get-frame-offset-b
   #:cone-twist-constraint/get-info-1
   #:cone-twist-constraint/get-info-1-non-virtual
   #:cone-twist-constraint/get-info-2
   #:cone-twist-constraint/get-info-2-non-virtual
   #:cone-twist-constraint/get-point-for-angle
   #:cone-twist-constraint/get-rigid-body-a
   #:cone-twist-constraint/get-rigid-body-b
   #:cone-twist-constraint/get-solve-swing-limit
   #:cone-twist-constraint/get-solve-twist-limit
   #:cone-twist-constraint/get-swing-span-1
   #:cone-twist-constraint/get-swing-span-2
   #:cone-twist-constraint/get-twist-angle
   #:cone-twist-constraint/get-twist-limit-sign
   #:cone-twist-constraint/get-twist-span
   #:cone-twist-constraint/is-past-swing-limit
   #:cone-twist-constraint/make-c++-array
   #:cone-twist-constraint/make-c++-instance
   #:cone-twist-constraint/serialize
   #:cone-twist-constraint/set-angular-only
   #:cone-twist-constraint/set-damping
   #:cone-twist-constraint/set-fix-thresh
   #:cone-twist-constraint/set-frames
   #:cone-twist-constraint/set-limit
   #:cone-twist-constraint/set-max-motor-impulse
   #:cone-twist-constraint/set-max-motor-impulse-normalized
   #:cone-twist-constraint/set-motor-target
   #:cone-twist-constraint/set-motor-target-in-constraint-space
   #:cone-twist-constraint/solve-constraint-obsolete
   #:cone-twist-constraint/update-rhs
   #:cone-twist-flags
   #:cone-twist-flags
   #:constraint
   #:constraint-params
   #:constraint-setting
   #:constraint-solver
   #:contact-pair-test
   #:contact-processing-threshold
   #:contact-processing-threshold
   #:contact-result-callback
   #:contact-test
   #:convex-from-world
   #:convex-hull-shape-data
   #:convex-hull-shape/add-point
   #:convex-hull-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:convex-hull-shape/calculate-serialize-buffer-size
   #:convex-hull-shape/delete-c++-array
   #:convex-hull-shape/delete-c++-instance
   #:convex-hull-shape/get-edge
   #:convex-hull-shape/get-name
   #:convex-hull-shape/get-num-edges
   #:convex-hull-shape/get-num-planes
   #:convex-hull-shape/get-num-points
   #:convex-hull-shape/get-num-vertices
   #:convex-hull-shape/get-plane
   #:convex-hull-shape/get-points
   #:convex-hull-shape/get-scaled-point
   #:convex-hull-shape/get-unscaled-points
   #:convex-hull-shape/get-vertex
   #:convex-hull-shape/is-inside
   #:convex-hull-shape/local-get-supporting-vertex
   #:convex-hull-shape/local-get-supporting-vertex-without-margin
   #:convex-hull-shape/make-c++-array
   #:convex-hull-shape/make-c++-instance
   #:convex-hull-shape/project
   #:convex-hull-shape/serialize
   #:convex-hull-shape/set-local-scaling
   #:convex-internal-shape-data
   #:convex-result-callback
   #:convex-sweep-test
   #:convex-to-world
   #:convex-triangle-mesh-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:convex-triangle-mesh-shape/calculate-principal-axis-transform
   #:convex-triangle-mesh-shape/delete-c++-array
   #:convex-triangle-mesh-shape/delete-c++-instance
   #:convex-triangle-mesh-shape/get-edge
   #:convex-triangle-mesh-shape/get-local-scaling
   #:convex-triangle-mesh-shape/get-mesh-interface
   #:convex-triangle-mesh-shape/get-name
   #:convex-triangle-mesh-shape/get-num-edges
   #:convex-triangle-mesh-shape/get-num-planes
   #:convex-triangle-mesh-shape/get-num-vertices
   #:convex-triangle-mesh-shape/get-plane
   #:convex-triangle-mesh-shape/get-vertex
   #:convex-triangle-mesh-shape/is-inside
   #:convex-triangle-mesh-shape/local-get-supporting-vertex
   #:convex-triangle-mesh-shape/local-get-supporting-vertex-without-margin
   #:convex-triangle-mesh-shape/make-c++-array
   #:convex-triangle-mesh-shape/make-c++-instance
   #:convex-triangle-mesh-shape/set-local-scaling
   #:cosine
   #:cprofile-iterator/enter/child
   #:cprofile-iterator/enter/largest/child
   #:cprofile-iterator/enter/parent
   #:cprofile-iterator/first
   #:cprofile-iterator/get/current/name
   #:cprofile-iterator/get/current/parent/name
   #:cprofile-iterator/get/current/parent/total/calls
   #:cprofile-iterator/get/current/parent/total/time
   #:cprofile-iterator/get/current/total/calls
   #:cprofile-iterator/get/current/total/time
   #:cprofile-iterator/get/current/user-pointer
   #:cprofile-iterator/is/done
   #:cprofile-iterator/is/root
   #:cprofile-iterator/next
   #:cprofile-iterator/set/current/user-pointer
   #:cprofile-manager/cleanup-memory
   #:cprofile-manager/dump-all
   #:cprofile-manager/dump-recursive
   #:cprofile-manager/get/frame/count/since/reset
   #:cprofile-manager/get/iterator
   #:cprofile-manager/get/time/since/reset
   #:cprofile-manager/increment/frame/counter
   #:cprofile-manager/release/iterator
   #:cprofile-manager/reset
   #:cprofile-manager/start/profile
   #:cprofile-manager/stop/profile
   #:cprofile-node/call
   #:cprofile-node/cleanup-memory
   #:cprofile-node/get-user-pointer
   #:cprofile-node/get/child
   #:cprofile-node/get/name
   #:cprofile-node/get/parent
   #:cprofile-node/get/sibling
   #:cprofile-node/get/sub/node
   #:cprofile-node/get/total/calls
   #:cprofile-node/get/total/time
   #:cprofile-node/reset
   #:cprofile-node/return
   #:cprofile-node/set-user-pointer
   #:create-proxy
   #:cross
   #:cupdates
   #:custom-collision-algorithm-max-element-size
   #:cylinder-shape-data
   #:cylinder-shape-x/batched-unit-vector-get-supporting-vertex-without-margin
   #:cylinder-shape-x/delete-c++-array
   #:cylinder-shape-x/delete-c++-instance
   #:cylinder-shape-x/get-name
   #:cylinder-shape-x/get-radius
   #:cylinder-shape-x/local-get-supporting-vertex-without-margin
   #:cylinder-shape-x/make-c++-array
   #:cylinder-shape-x/make-c++-instance
   #:cylinder-shape-z/batched-unit-vector-get-supporting-vertex-without-margin
   #:cylinder-shape-z/delete-c++-array
   #:cylinder-shape-z/delete-c++-instance
   #:cylinder-shape-z/get-name
   #:cylinder-shape-z/get-radius
   #:cylinder-shape-z/local-get-supporting-vertex-without-margin
   #:cylinder-shape-z/make-c++-array
   #:cylinder-shape-z/make-c++-instance
   #:cylinder-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:cylinder-shape/calculate-local-inertia
   #:cylinder-shape/calculate-serialize-buffer-size
   #:cylinder-shape/delete-c++-array
   #:cylinder-shape/delete-c++-instance
   #:cylinder-shape/get-aabb
   #:cylinder-shape/get-anisotropic-rolling-friction-direction
   #:cylinder-shape/get-half-extents-with-margin
   #:cylinder-shape/get-half-extents-without-margin
   #:cylinder-shape/get-name
   #:cylinder-shape/get-radius
   #:cylinder-shape/get-up-axis
   #:cylinder-shape/local-get-supporting-vertex
   #:cylinder-shape/local-get-supporting-vertex-without-margin
   #:cylinder-shape/make-c++-array
   #:cylinder-shape/make-c++-instance
   #:cylinder-shape/serialize
   #:cylinder-shape/set-local-scaling
   #:cylinder-shape/set-margin
   #:damping
   #:dbg-draw-size
   #:dbvt-broadphase
   #:dbvt-proxy
   #:deactivation-time
   #:deactivation-time
   #:debug-draw-constraint
   #:debug-draw-modes
   #:debug-draw-modes
   #:debug-draw-object
   #:debug-draw-world
   #:debug-drawer
   #:default-collision-configuration/get-collision-algorithm-create-func
   #:default-collision-configuration/get-collision-algorithm-pool
   #:default-collision-configuration/get-persistent-manifold-pool
   #:default-collision-configuration/get-simplex-solver
   #:default-collision-configuration/set-convex-convex-multipoint-iterations
   #:default-collision-configuration/set-plane-convex-multipoint-iterations
   #:default-collision-construction-info
   #:default-max-collision-algorithm-pool-size
   #:default-max-persistent-manifold-pool-size
   #:default-motion-state
   #:default-serializer/allocate
   #:default-serializer/finalize-chunk
   #:default-serializer/find-name-for-pointer
   #:default-serializer/finish-serialization
   #:default-serializer/get-buffer-pointer
   #:default-serializer/get-current-buffer-size
   #:default-serializer/get-serialization-flags
   #:default-serializer/get-unique-pointer
   #:default-serializer/internal-alloc
   #:default-serializer/register-name-for-pointer
   #:default-serializer/serialize-name
   #:default-serializer/set-serialization-flags
   #:default-serializer/start-serialization
   #:default-serializer/write-header
   #:deferedcollide
   #:degrees
   #:delete-c++-array
   #:delete-c++-instance
   #:delete/bt-32-bit-axis-sweep-3
   #:delete/bt-angular-limit
   #:delete/bt-axis-sweep-3
   #:delete/bt-box-shape
   #:delete/bt-bu/simplex-1to-4
   #:delete/bt-bvh-triangle-mesh-shape
   #:delete/bt-capsule-shape
   #:delete/bt-capsule-shape-x
   #:delete/bt-capsule-shape-z
   #:delete/bt-chunk
   #:delete/bt-clock
   #:delete/bt-collision-dispatcher
   #:delete/bt-collision-world
   #:delete/bt-compound-shape
   #:delete/bt-cone-shape
   #:delete/bt-cone-shape-x
   #:delete/bt-cone-shape-z
   #:delete/bt-cone-twist-constraint
   #:delete/bt-convex-hull-shape
   #:delete/bt-convex-triangle-mesh-shape
   #:delete/bt-cylinder-shape
   #:delete/bt-cylinder-shape-x
   #:delete/bt-cylinder-shape-z
   #:delete/bt-default-collision-configuration
   #:delete/bt-default-serializer
   #:delete/bt-discrete-dynamics-world
   #:delete/bt-empty-shape
   #:delete/bt-fixed-constraint
   #:delete/bt-gear-constraint
   #:delete/bt-generic-6-dof-constraint
   #:delete/bt-generic-6-dof-spring-constraint
   #:delete/bt-hinge-2-constraint
   #:delete/bt-hinge-constraint
   #:delete/bt-idebug-draw
   #:delete/bt-matrix-3x3
   #:delete/bt-motion-state
   #:delete/bt-multi-sap-broadphase
   #:delete/bt-multi-sphere-shape
   #:delete/bt-point-2-point-constraint
   #:delete/bt-quaternion
   #:delete/bt-rigid-body
   #:delete/bt-rotational-limit-motor
   #:delete/bt-scaled-bvh-triangle-mesh-shape
   #:delete/bt-sequential-impulse-constraint-solver
   #:delete/bt-serializer
   #:delete/bt-simple-broadphase
   #:delete/bt-simple-dynamics-world
   #:delete/bt-slider-constraint
   #:delete/bt-sphere-shape
   #:delete/bt-sphere-sphere-collision-algorithm
   #:delete/bt-static-plane-shape
   #:delete/bt-transform
   #:delete/bt-translational-limit-motor
   #:delete/bt-triangle-index-vertex-array
   #:delete/bt-triangle-mesh
   #:delete/bt-triangle-mesh-shape
   #:delete/bt-typed-constraint
   #:delete/bt-uniform-scaling-shape
   #:delete/bt-universal-constraint
   #:delete/bt-vector-3
   #:delete/bt-vector-4
   #:delete/cprofile-iterator
   #:delete/cprofile-manager
   #:delete/cprofile-node
   #:delete/cprofile-sample
   #:destroy-proxy
   #:disable-collisions-between-linked-bodies
   #:discrete-dynamics-world/add-action
   #:discrete-dynamics-world/add-character
   #:discrete-dynamics-world/add-collision-object
   #:discrete-dynamics-world/add-constraint
   #:discrete-dynamics-world/add-rigid-body
   #:discrete-dynamics-world/add-rigid-body/with-group&mask
   #:discrete-dynamics-world/add-vehicle
   #:discrete-dynamics-world/apply-gravity
   #:discrete-dynamics-world/clear-forces
   #:discrete-dynamics-world/debug-draw-constraint
   #:discrete-dynamics-world/debug-draw-world
   #:discrete-dynamics-world/delete-c++-array
   #:discrete-dynamics-world/delete-c++-instance
   #:discrete-dynamics-world/get-apply-speculative-contact-restitution
   #:discrete-dynamics-world/get-collision-world
   #:discrete-dynamics-world/get-constraint
   #:discrete-dynamics-world/get-constraint-solver
   #:discrete-dynamics-world/get-gravity
   #:discrete-dynamics-world/get-latency-motion-state-interpolation
   #:discrete-dynamics-world/get-num-constraints
   #:discrete-dynamics-world/get-simulation-island-manager
   #:discrete-dynamics-world/get-synchronize-all-motion-states
   #:discrete-dynamics-world/get-world-type
   #:discrete-dynamics-world/make-c++-array
   #:discrete-dynamics-world/make-c++-instance
   #:discrete-dynamics-world/remove-action
   #:discrete-dynamics-world/remove-character
   #:discrete-dynamics-world/remove-collision-object
   #:discrete-dynamics-world/remove-constraint
   #:discrete-dynamics-world/remove-rigid-body
   #:discrete-dynamics-world/remove-vehicle
   #:discrete-dynamics-world/serialize
   #:discrete-dynamics-world/set-apply-speculative-contact-restitution
   #:discrete-dynamics-world/set-constraint-solver
   #:discrete-dynamics-world/set-gravity
   #:discrete-dynamics-world/set-latency-motion-state-interpolation
   #:discrete-dynamics-world/set-num-tasks
   #:discrete-dynamics-world/set-synchronize-all-motion-states
   #:discrete-dynamics-world/step-simulation
   #:discrete-dynamics-world/synchronize-motion-states
   #:discrete-dynamics-world/synchronize-single-motion-state
   #:discrete-dynamics-world/update-vehicles
   #:dispatch-info
   #:dispatcher
   #:dispatcher-flags
   #:dispatcher-flags
   #:distance
   #:distance-2
   #:dot
   #:dupdates
   #:el
   #:empty-shape/calculate-local-inertia
   #:empty-shape/delete-c++-array
   #:empty-shape/delete-c++-instance
   #:empty-shape/get-aabb
   #:empty-shape/get-local-scaling
   #:empty-shape/get-name
   #:empty-shape/make-c++-array
   #:empty-shape/make-c++-instance
   #:empty-shape/process-all-triangles
   #:empty-shape/set-local-scaling
   #:enable-angular-motor
   #:equals
   #:equilibrium-point
   #:exponent
   #:fabs
   #:fixed-constraint/get-info-1
   #:fixed-constraint/get-info-2
   #:fixedleft
   #:flags
   #:floats
   #:fmod
   #:force-activation-state
   #:force-update-all-aabbs
   #:friction
   #:friction
   #:fsel
   #:fupdates
   #:fuzzy-zero
   #:gear-constraint-double-data
   #:gear-constraint-float-data
   #:gear-constraint/calculate-serialize-buffer-size
   #:gear-constraint/get-axis-a
   #:gear-constraint/get-axis-b
   #:gear-constraint/get-info-1
   #:gear-constraint/get-info-2
   #:gear-constraint/get-ratio
   #:gear-constraint/serialize
   #:gear-constraint/set-axis-a
   #:gear-constraint/set-axis-b
   #:gear-constraint/set-ratio
   #:generic-6-dof-constraint-data
   #:generic-6-dof-constraint-double-data-2
   #:generic-6-dof-constraint/build-jacobian
   #:generic-6-dof-constraint/calc-anchor-pos
   #:generic-6-dof-constraint/calculate-serialize-buffer-size
   #:generic-6-dof-constraint/calculate-transforms
   #:generic-6-dof-constraint/delete-c++-array
   #:generic-6-dof-constraint/delete-c++-instance
   #:generic-6-dof-constraint/get-angle
   #:generic-6-dof-constraint/get-angular-lower-limit
   #:generic-6-dof-constraint/get-angular-upper-limit
   #:generic-6-dof-constraint/get-axis
   #:generic-6-dof-constraint/get-calculated-transform-a
   #:generic-6-dof-constraint/get-calculated-transform-b
   #:generic-6-dof-constraint/get-frame-offset-a
   #:generic-6-dof-constraint/get-frame-offset-b
   #:generic-6-dof-constraint/get-info-1
   #:generic-6-dof-constraint/get-info-1-non-virtual
   #:generic-6-dof-constraint/get-info-2
   #:generic-6-dof-constraint/get-info-2-non-virtual
   #:generic-6-dof-constraint/get-linear-lower-limit
   #:generic-6-dof-constraint/get-linear-upper-limit
   #:generic-6-dof-constraint/get-relative-pivot-position
   #:generic-6-dof-constraint/get-rotational-limit-motor
   #:generic-6-dof-constraint/get-translational-limit-motor
   #:generic-6-dof-constraint/get-use-frame-offset
   #:generic-6-dof-constraint/get/limit/motor/info-2
   #:generic-6-dof-constraint/is-limited
   #:generic-6-dof-constraint/m/use-solve-constraint-obsolete/get
   #:generic-6-dof-constraint/m/use-solve-constraint-obsolete/set
   #:generic-6-dof-constraint/make-c++-array
   #:generic-6-dof-constraint/make-c++-instance
   #:generic-6-dof-constraint/serialize
   #:generic-6-dof-constraint/set-angular-lower-limit
   #:generic-6-dof-constraint/set-angular-upper-limit
   #:generic-6-dof-constraint/set-axis
   #:generic-6-dof-constraint/set-frames
   #:generic-6-dof-constraint/set-limit
   #:generic-6-dof-constraint/set-linear-lower-limit
   #:generic-6-dof-constraint/set-linear-upper-limit
   #:generic-6-dof-constraint/set-use-frame-offset
   #:generic-6-dof-constraint/test-angular-limit-motor
   #:generic-6-dof-constraint/update-rhs
   #:generic-6-dof-spring-constraint-data
   #:generic-6-dof-spring-constraint-double-data-2
   #:generic-6-dof-spring-constraint/calculate-serialize-buffer-size
   #:generic-6-dof-spring-constraint/delete-c++-array
   #:generic-6-dof-spring-constraint/delete-c++-instance
   #:generic-6-dof-spring-constraint/enable-spring
   #:generic-6-dof-spring-constraint/get-info-2
   #:generic-6-dof-spring-constraint/make-c++-array
   #:generic-6-dof-spring-constraint/make-c++-instance
   #:generic-6-dof-spring-constraint/serialize
   #:generic-6-dof-spring-constraint/set-axis
   #:generic-6-dof-spring-constraint/set-damping
   #:generic-6-dof-spring-constraint/set-equilibrium-point
   #:generic-6-dof-spring-constraint/set-stiffness
   #:get-aabb
   #:get-broadphase-aabb
   #:get-broadphase-handle
   #:get-infinity-mask
   #:get-next-free
   #:get-object-type
   #:get-overlapping-pair-cache
   #:get-velocity-prediction
   #:get-version
   #:get-world-transform
   #:gid
   #:graphics-world-trans
   #:gravity
   #:gravity
   #:gravity-acceleration
   #:greater-equal
   #:has-anisotropic-friction
   #:has-anisotropic-friction
   #:has-anisotropic-friction-p
   #:has-contact-response-p
   #:has-hit
   #:hinge-2-constraint/delete-c++-array
   #:hinge-2-constraint/delete-c++-instance
   #:hinge-2-constraint/get-anchor
   #:hinge-2-constraint/get-anchor-2
   #:hinge-2-constraint/get-angle-1
   #:hinge-2-constraint/get-angle-2
   #:hinge-2-constraint/get-axis-1
   #:hinge-2-constraint/get-axis-2
   #:hinge-2-constraint/make-c++-array
   #:hinge-2-constraint/make-c++-instance
   #:hinge-2-constraint/set-lower-limit
   #:hinge-2-constraint/set-upper-limit
   #:hinge-constraint-double-data
   #:hinge-constraint-double-data-2
   #:hinge-constraint-float-data
   #:hinge-constraint/build-jacobian
   #:hinge-constraint/calculate-serialize-buffer-size
   #:hinge-constraint/delete-c++-array
   #:hinge-constraint/delete-c++-instance
   #:hinge-constraint/enable-angular-motor
   #:hinge-constraint/enable-motor
   #:hinge-constraint/get-aframe
   #:hinge-constraint/get-angular-only
   #:hinge-constraint/get-bframe
   #:hinge-constraint/get-enable-angular-motor
   #:hinge-constraint/get-frame-offset-a
   #:hinge-constraint/get-frame-offset-b
   #:hinge-constraint/get-hinge-angle
   #:hinge-constraint/get-info-1
   #:hinge-constraint/get-info-1-non-virtual
   #:hinge-constraint/get-info-2
   #:hinge-constraint/get-info-2-internal
   #:hinge-constraint/get-info-2-internal-using-frame-offset
   #:hinge-constraint/get-info-2-non-virtual
   #:hinge-constraint/get-limit-sign
   #:hinge-constraint/get-lower-limit
   #:hinge-constraint/get-max-motor-impulse
   #:hinge-constraint/get-motor-target-velosity
   #:hinge-constraint/get-rigid-body-a
   #:hinge-constraint/get-rigid-body-b
   #:hinge-constraint/get-solve-limit
   #:hinge-constraint/get-upper-limit
   #:hinge-constraint/get-use-frame-offset
   #:hinge-constraint/make-c++-array
   #:hinge-constraint/make-c++-instance
   #:hinge-constraint/serialize
   #:hinge-constraint/set-angular-only
   #:hinge-constraint/set-axis
   #:hinge-constraint/set-limit/naked
   #:hinge-constraint/set-limit/softness
   #:hinge-constraint/set-limit/softness&bias
   #:hinge-constraint/set-limit/softness&bias&relaxation
   #:hinge-constraint/set-max-motor-impulse
   #:hinge-constraint/set-motor-target/q-a-in-b
   #:hinge-constraint/set-motor-target/target-angle
   #:hinge-constraint/set-use-frame-offset
   #:hinge-constraint/test-limit
   #:hinge-constraint/update-rhs
   #:hinge-flags
   #:hinge-flags
   #:hit-collision-object
   #:hit-fraction
   #:hit-fraction
   #:hit-fractions
   #:hit-normal-local
   #:hit-normal-world
   #:hit-point-local
   #:hit-point-world
   #:idebug-draw/draw-3d-text
   #:idebug-draw/draw-aabb
   #:idebug-draw/draw-arc
   #:idebug-draw/draw-box
   #:idebug-draw/draw-capsule
   #:idebug-draw/draw-cone
   #:idebug-draw/draw-contact-point
   #:idebug-draw/draw-cylinder
   #:idebug-draw/draw-line
   #:idebug-draw/draw-plane
   #:idebug-draw/draw-sphere
   #:idebug-draw/draw-sphere-patch
   #:idebug-draw/draw-transform
   #:idebug-draw/draw-triangle
   #:idebug-draw/get-debug-mode
   #:idebug-draw/report-error-warning
   #:idebug-draw/set-debug-mode
   #:impulse-clamp
   #:index-type
   #:indexed-mesh
   #:initialize-instance
   #:internal-get-extension-pointer
   #:internal-set-extension-pointer
   #:internal-type
   #:internal-type
   #:interpolation-angular-velocity
   #:interpolation-angular-velocity
   #:interpolation-linear-velocity
   #:interpolation-linear-velocity
   #:interpolation-world-transform
   #:interpolation-world-transform
   #:inv-inertia-local
   #:inv-inertia-tensor-world
   #:inverse
   #:inverse-mass
   #:is-enabled
   #:is-negative
   #:island-tag
   #:island-tag-1
   #:island-tag-1
   #:joint-feedback
   #:kinematic-object-p
   #:large-dot
   #:latency-motion-state-interpolation
   #:leaf
   #:limit-softness
   #:linear-damping
   #:linear-factor
   #:linear-lower-limit
   #:linear-sleeping-threshold
   #:linear-upper-limit
   #:linear-velocity
   #:links
   #:local-convex-result
   #:local-position-array-ptr
   #:local-position-array-size
   #:local-ray-result
   #:local-scaling
   #:local-shape-info
   #:logarithm
   #:lower-limit
   #:machine-is-little-endian
   #:make-32-bit-axis-sweep-3
   #:make-angular-limit
   #:make-axis-sweep-3
   #:make-box-shape
   #:make-bu/simplex-1to-4
   #:make-bvh-triangle-mesh-shape
   #:make-c++-array
   #:make-c++-instance
   #:make-capsule-shape
   #:make-capsule-shape-x
   #:make-capsule-shape-z
   #:make-chunk
   #:make-clock
   #:make-collision-dispatcher
   #:make-collision-object
   #:make-collision-world
   #:make-collision-world
   #:make-compound-shape
   #:make-cone-shape
   #:make-cone-shape-x
   #:make-cone-shape-z
   #:make-cone-twist-constraint
   #:make-convex-hull-shape
   #:make-convex-triangle-mesh-shape
   #:make-cprofile-manager
   #:make-cprofile-node
   #:make-cprofile-sample
   #:make-cylinder-shape
   #:make-cylinder-shape-x
   #:make-cylinder-shape-z
   #:make-default-collision-configuration
   #:make-default-serializer
   #:make-discrete-dynamics-world
   #:make-discrete-dynamics-world
   #:make-empty-shape
   #:make-fixed-constraint
   #:make-gear-constraint
   #:make-gear-constraint/without-ratio
   #:make-generic-6-dof-constraint
   #:make-generic-6-dof-spring-constraint
   #:make-hinge-2-constraint
   #:make-hinge-constraint
   #:make-matrix-3x3/9
   #:make-matrix-3x3/copy
   #:make-matrix-3x3/naked
   #:make-matrix-3x3/quaternion
   #:make-multi-sphere-shape
   #:make-point-2-point-constraint
   #:make-quaternion
   #:make-rigid-body
   #:make-rotational-limit-motor
   #:make-scaled-bvh-triangle-mesh-shape
   #:make-sequential-impulse-constraint-solver
   #:make-simple-broadphase
   #:make-simple-dynamics-world
   #:make-simple-dynamics-world
   #:make-slider-constraint
   #:make-sphere-shape
   #:make-sphere-sphere-collision-algorithm
   #:make-static-plane-shape
   #:make-transform
   #:make-transform/naked
   #:make-transform/with-b
   #:make-transform/with-b&c
   #:make-transform/with-other
   #:make-transform/with-q
   #:make-transform/with-q&c
   #:make-translational-limit-motor
   #:make-triangle-index-vertex-array
   #:make-triangle-mesh
   #:make-uniform-scaling-shape
   #:make-universal-constraint
   #:make-vector3
   #:make-vector3
   #:make-vector4
   #:matrix-3x3-double-data
   #:matrix-3x3-float-data
   #:matrix-3x3/absolute
   #:matrix-3x3/adjoint
   #:matrix-3x3/aref
   #:matrix-3x3/assign-value
   #:matrix-3x3/cofac
   #:matrix-3x3/de-serialize
   #:matrix-3x3/de-serialize-double
   #:matrix-3x3/de-serialize-float
   #:matrix-3x3/decrement
   #:matrix-3x3/determinant
   #:matrix-3x3/diagonalize
   #:matrix-3x3/get-column
   #:matrix-3x3/get-euler-ypr
   #:matrix-3x3/get-euler-zyx
   #:matrix-3x3/get-identity
   #:matrix-3x3/get-open-glsub-matrix
   #:matrix-3x3/get-rotation
   #:matrix-3x3/get-row
   #:matrix-3x3/increment
   #:matrix-3x3/inverse
   #:matrix-3x3/multiply-and-assign
   #:matrix-3x3/scaled
   #:matrix-3x3/serialize
   #:matrix-3x3/serialize-float
   #:matrix-3x3/set-euler-ypr
   #:matrix-3x3/set-euler-zyx
   #:matrix-3x3/set-from-open-glsub-matrix
   #:matrix-3x3/set-identity
   #:matrix-3x3/set-rotation
   #:matrix-3x3/set-value
   #:matrix-3x3/tdotx
   #:matrix-3x3/tdoty
   #:matrix-3x3/tdotz
   #:matrix-3x3/times-transpose
   #:matrix-3x3/transpose
   #:matrix-3x3/transpose-times
   #:max-motor-impulse
   #:merges-simulation-islands
   #:mesh-interface
   #:motion-state/get-world-transform
   #:motion-state/set-world-transform
   #:motor-target-velocity
   #:multi-sap-broadphase/add-to-child-broadphase
   #:multi-sap-broadphase/build-tree
   #:multi-sap-broadphase/calculate-overlapping-pairs
   #:multi-sap-broadphase/create-proxy
   #:multi-sap-broadphase/destroy-proxy
   #:multi-sap-broadphase/get-aabb
   #:multi-sap-broadphase/get-broadphase-aabb
   #:multi-sap-broadphase/get-broadphase-array
   #:multi-sap-broadphase/get-overlapping-pair-cache
   #:multi-sap-broadphase/print-stats
   #:multi-sap-broadphase/quicksort
   #:multi-sap-broadphase/ray-test
   #:multi-sap-broadphase/reset-pool
   #:multi-sap-broadphase/set-aabb
   #:multi-sap-broadphase/test-aabb-overlap
   #:multi-sphere-shape-data
   #:multi-sphere-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:multi-sphere-shape/calculate-local-inertia
   #:multi-sphere-shape/calculate-serialize-buffer-size
   #:multi-sphere-shape/delete-c++-array
   #:multi-sphere-shape/delete-c++-instance
   #:multi-sphere-shape/get-name
   #:multi-sphere-shape/get-sphere-count
   #:multi-sphere-shape/get-sphere-position
   #:multi-sphere-shape/get-sphere-radius
   #:multi-sphere-shape/local-get-supporting-vertex-without-margin
   #:multi-sphere-shape/make-c++-array
   #:multi-sphere-shape/make-c++-instance
   #:multi-sphere-shape/serialize
   #:name
   #:name
   #:needcleanup
   #:needs-collision
   #:needs-feedback
   #:newpairs
   #:next-free
   #:node
   #:normalize-angle
   #:num-child-shapes
   #:num-collision-objects
   #:num-constraints
   #:num-tasks
   #:num-triangles
   #:num-unscaled-points
   #:num-vertices
   #:object-type
   #:origin
   #:override-num-solver-iterations
   #:pad
   #:pad-3
   #:padding
   #:padding
   #:padding-1
   #:padding-3
   #:pair-cache
   #:paircache
   #:perform-deferred-removal
   #:perform-discrete-collision-detection
   #:persistent-manifold-pool
   #:pid
   #:pivot-in-a
   #:pivot-in-b
   #:plane-constant
   #:plane-normal
   #:point-2-point-constraint-double-data
   #:point-2-point-constraint-double-data-2
   #:point-2-point-constraint-float-data
   #:point-2-point-constraint/build-jacobian
   #:point-2-point-constraint/calculate-serialize-buffer-size
   #:point-2-point-constraint/delete-c++-array
   #:point-2-point-constraint/delete-c++-instance
   #:point-2-point-constraint/get-info-1
   #:point-2-point-constraint/get-info-1-non-virtual
   #:point-2-point-constraint/get-info-2
   #:point-2-point-constraint/get-info-2-non-virtual
   #:point-2-point-constraint/get-pivot-in-a
   #:point-2-point-constraint/get-pivot-in-b
   #:point-2-point-constraint/m/setting/get
   #:point-2-point-constraint/m/setting/set
   #:point-2-point-constraint/m/use-solve-constraint-obsolete/get
   #:point-2-point-constraint/m/use-solve-constraint-obsolete/set
   #:point-2-point-constraint/make-c++-array
   #:point-2-point-constraint/make-c++-instance
   #:point-2-point-constraint/serialize
   #:point-2-point-constraint/set-pivot-a
   #:point-2-point-constraint/set-pivot-b
   #:point-2-point-constraint/update-rhs
   #:point-2-point-flags
   #:point-2-point-flags
   #:pointer-uid
   #:pos
   #:position-and-radius
   #:power
   #:prediction
   #:print-stats
   #:qlength
   #:quantized-double-bvh
   #:quantized-float-bvh
   #:quat-rotate
   #:quaternion///neg//
   #:quaternion/add
   #:quaternion/angle
   #:quaternion/angle
   #:quaternion/angle-shortest-path
   #:quaternion/decrement
   #:quaternion/divide
   #:quaternion/divide-and-assign
   #:quaternion/dot
   #:quaternion/farthest
   #:quaternion/get-angle
   #:quaternion/get-angle-shortest-path
   #:quaternion/get-axis
   #:quaternion/get-identity
   #:quaternion/get-w
   #:quaternion/increment
   #:quaternion/inverse
   #:quaternion/length
   #:quaternion/length-2
   #:quaternion/multiply
   #:quaternion/multiply-and-assign
   #:quaternion/nearest
   #:quaternion/normalize
   #:quaternion/normalized
   #:quaternion/set-euler
   #:quaternion/set-euler-zyx
   #:quaternion/set-rotation
   #:quaternion/slerp
   #:quaternion/subtract
   #:radians
   #:radius
   #:ray-from-world
   #:ray-result-callback
   #:ray-test
   #:ray-test
   #:ray-to-world
   #:rb-a
   #:rb-aframe
   #:rb-b
   #:rb-bframe
   #:relaxation-factor
   #:releasepaircache
   #:remove-action
   #:remove-character
   #:remove-collision-object
   #:remove-constraint
   #:remove-rigid-body
   #:remove-vehicle
   #:reset-pool
   #:restitution
   #:restitution
   #:rigid-body-double-data
   #:rigid-body-flags
   #:rigid-body-flags
   #:rigid-body-float-data
   #:rigid-body/add-constraint-ref
   #:rigid-body/apply-central-force
   #:rigid-body/apply-central-impulse
   #:rigid-body/apply-damping
   #:rigid-body/apply-force
   #:rigid-body/apply-gravity
   #:rigid-body/apply-impulse
   #:rigid-body/apply-torque
   #:rigid-body/apply-torque-impulse
   #:rigid-body/calculate-serialize-buffer-size
   #:rigid-body/check-collide-with-override
   #:rigid-body/clear-forces
   #:rigid-body/compute-angular-impulse-denominator
   #:rigid-body/compute-gyroscopic-force
   #:rigid-body/compute-impulse-denominator
   #:rigid-body/get-aabb
   #:rigid-body/get-angular-damping
   #:rigid-body/get-angular-factor
   #:rigid-body/get-angular-sleeping-threshold
   #:rigid-body/get-angular-velocity
   #:rigid-body/get-broadphase-proxy
   #:rigid-body/get-center-of-mass-position
   #:rigid-body/get-center-of-mass-transform
   #:rigid-body/get-collision-shape
   #:rigid-body/get-constraint-ref
   #:rigid-body/get-flags
   #:rigid-body/get-gravity
   #:rigid-body/get-inv-inertia-diag-local
   #:rigid-body/get-inv-inertia-tensor-world
   #:rigid-body/get-inv-mass
   #:rigid-body/get-linear-damping
   #:rigid-body/get-linear-factor
   #:rigid-body/get-linear-sleeping-threshold
   #:rigid-body/get-linear-velocity
   #:rigid-body/get-motion-state
   #:rigid-body/get-num-constraint-refs
   #:rigid-body/get-orientation
   #:rigid-body/get-total-force
   #:rigid-body/get-total-torque
   #:rigid-body/get-velocity-in-local-point
   #:rigid-body/integrate-velocities
   #:rigid-body/is-in-world
   #:rigid-body/m/contact-solver-type/get
   #:rigid-body/m/contact-solver-type/set
   #:rigid-body/m/friction-solver-type/get
   #:rigid-body/m/friction-solver-type/set
   #:rigid-body/predict-integrated-transform
   #:rigid-body/proceed-to-transform
   #:rigid-body/remove-constraint-ref
   #:rigid-body/save-kinematic-state
   #:rigid-body/serialize
   #:rigid-body/serialize-single-object
   #:rigid-body/set-angular-factor
   #:rigid-body/set-angular-velocity
   #:rigid-body/set-center-of-mass-transform
   #:rigid-body/set-damping
   #:rigid-body/set-flags
   #:rigid-body/set-gravity
   #:rigid-body/set-inv-inertia-diag-local
   #:rigid-body/set-linear-factor
   #:rigid-body/set-linear-velocity
   #:rigid-body/set-mass-props
   #:rigid-body/set-motion-state
   #:rigid-body/set-new-broadphase-proxy
   #:rigid-body/set-sleeping-thresholds
   #:rigid-body/translate
   #:rigid-body/upcast
   #:rigid-body/update-deactivation
   #:rigid-body/update-inertia-tensor
   #:rigid-body/wants-sleeping
   #:rolling-friction
   #:rolling-friction
   #:root-collision-shape
   #:root-collision-shape
   #:rotational-limit-motor/is-limited
   #:rotational-limit-motor/m/accumulated-impulse/get
   #:rotational-limit-motor/m/accumulated-impulse/set
   #:rotational-limit-motor/m/bounce/get
   #:rotational-limit-motor/m/bounce/set
   #:rotational-limit-motor/m/current-limit-error/get
   #:rotational-limit-motor/m/current-limit-error/set
   #:rotational-limit-motor/m/current-limit/get
   #:rotational-limit-motor/m/current-limit/set
   #:rotational-limit-motor/m/current-position/get
   #:rotational-limit-motor/m/current-position/set
   #:rotational-limit-motor/m/damping/get
   #:rotational-limit-motor/m/damping/set
   #:rotational-limit-motor/m/enable-motor/get
   #:rotational-limit-motor/m/enable-motor/set
   #:rotational-limit-motor/m/hi-limit/get
   #:rotational-limit-motor/m/hi-limit/set
   #:rotational-limit-motor/m/limit-softness/get
   #:rotational-limit-motor/m/limit-softness/set
   #:rotational-limit-motor/m/lo-limit/get
   #:rotational-limit-motor/m/lo-limit/set
   #:rotational-limit-motor/m/max-limit-force/get
   #:rotational-limit-motor/m/max-limit-force/set
   #:rotational-limit-motor/m/max-motor-force/get
   #:rotational-limit-motor/m/max-motor-force/set
   #:rotational-limit-motor/m/normal-cfm/get
   #:rotational-limit-motor/m/normal-cfm/set
   #:rotational-limit-motor/m/stop-cfm/get
   #:rotational-limit-motor/m/stop-cfm/set
   #:rotational-limit-motor/m/stop-erp/get
   #:rotational-limit-motor/m/stop-erp/set
   #:rotational-limit-motor/m/target-velocity/get
   #:rotational-limit-motor/m/target-velocity/set
   #:rotational-limit-motor/need-apply-torques
   #:rotational-limit-motor/solve-angular-limits
   #:rotational-limit-motor/test-limit-value
   #:scaled-bvh-triangle-mesh-shape/calculate-local-inertia
   #:scaled-bvh-triangle-mesh-shape/calculate-serialize-buffer-size
   #:scaled-bvh-triangle-mesh-shape/delete-c++-array
   #:scaled-bvh-triangle-mesh-shape/delete-c++-instance
   #:scaled-bvh-triangle-mesh-shape/get-aabb
   #:scaled-bvh-triangle-mesh-shape/get-child-shape
   #:scaled-bvh-triangle-mesh-shape/get-local-scaling
   #:scaled-bvh-triangle-mesh-shape/get-name
   #:scaled-bvh-triangle-mesh-shape/make-c++-array
   #:scaled-bvh-triangle-mesh-shape/make-c++-instance
   #:scaled-bvh-triangle-mesh-shape/process-all-triangles
   #:scaled-bvh-triangle-mesh-shape/serialize
   #:scaled-bvh-triangle-mesh-shape/set-local-scaling
   #:scaled-triangle-mesh-shape-data
   #:select
   #:sequential-impulse-constraint-solver/bt-rand-2
   #:sequential-impulse-constraint-solver/bt-rand-int-2
   #:sequential-impulse-constraint-solver/delete-c++-array
   #:sequential-impulse-constraint-solver/delete-c++-instance
   #:sequential-impulse-constraint-solver/get-rand-seed
   #:sequential-impulse-constraint-solver/get-solver-type
   #:sequential-impulse-constraint-solver/make-c++-array
   #:sequential-impulse-constraint-solver/make-c++-instance
   #:sequential-impulse-constraint-solver/reset
   #:sequential-impulse-constraint-solver/set-rand-seed
   #:sequential-impulse-constraint-solver/solve-group
   #:serialization-flags
   #:serialization-flags
   #:serialize
   #:serialize-single-object
   #:serializer/allocate
   #:serializer/finalize-chunk
   #:serializer/find-name-for-pointer
   #:serializer/find-pointer
   #:serializer/finish-serialization
   #:serializer/get-buffer-pointer
   #:serializer/get-current-buffer-size
   #:serializer/get-serialization-flags
   #:serializer/get-unique-pointer
   #:serializer/register-name-for-pointer
   #:serializer/serialize-name
   #:serializer/set-serialization-flags
   #:serializer/start-serialization
   #:set-aabb
   #:set-aabb-force-update
   #:set-next-free
   #:set-velocity-prediction
   #:set-world-transform
   #:setf
   #:sets
   #:shape-part
   #:shortest-arc-quat
   #:shortest-arc-quat-normalize-2
   #:simple-broadphase
   #:simple-broadphase-proxy
   #:simple-broadphase/aabb-overlap
   #:simple-broadphase/aabb-test
   #:simple-broadphase/calculate-overlapping-pairs
   #:simple-broadphase/create-proxy
   #:simple-broadphase/destroy-proxy
   #:simple-broadphase/get-aabb
   #:simple-broadphase/get-broadphase-aabb
   #:simple-broadphase/get-overlapping-pair-cache
   #:simple-broadphase/print-stats
   #:simple-broadphase/ray-test
   #:simple-broadphase/set-aabb
   #:simple-broadphase/test-aabb-overlap
   #:simple-dynamics-world/add-action
   #:simple-dynamics-world/add-rigid-body
   #:simple-dynamics-world/clear-forces
   #:simple-dynamics-world/debug-draw-world
   #:simple-dynamics-world/get-constraint-solver
   #:simple-dynamics-world/get-gravity
   #:simple-dynamics-world/get-world-type
   #:simple-dynamics-world/remove-action
   #:simple-dynamics-world/remove-collision-object
   #:simple-dynamics-world/remove-rigid-body
   #:simple-dynamics-world/set-constraint-solver
   #:simple-dynamics-world/set-gravity
   #:simple-dynamics-world/step-simulation
   #:simple-dynamics-world/synchronize-motion-states
   #:simple-dynamics-world/update-aabbs
   #:simulation-island-manager
   #:sine
   #:slerp
   #:slider-constraint-data
   #:slider-constraint-double-data
   #:slider-constraint/calculate-serialize-buffer-size
   #:slider-constraint/calculate-transforms
   #:slider-constraint/delete-c++-array
   #:slider-constraint/delete-c++-instance
   #:slider-constraint/get-ancor-in-a
   #:slider-constraint/get-ancor-in-b
   #:slider-constraint/get-ang-depth
   #:slider-constraint/get-angular-pos
   #:slider-constraint/get-calculated-transform-a
   #:slider-constraint/get-calculated-transform-b
   #:slider-constraint/get-damping-dir-ang
   #:slider-constraint/get-damping-dir-lin
   #:slider-constraint/get-damping-lim-ang
   #:slider-constraint/get-damping-lim-lin
   #:slider-constraint/get-damping-ortho-ang
   #:slider-constraint/get-damping-ortho-lin
   #:slider-constraint/get-frame-offset-a
   #:slider-constraint/get-frame-offset-b
   #:slider-constraint/get-info-1
   #:slider-constraint/get-info-1-non-virtual
   #:slider-constraint/get-info-2
   #:slider-constraint/get-info-2-non-virtual
   #:slider-constraint/get-lin-depth
   #:slider-constraint/get-linear-pos
   #:slider-constraint/get-lower-ang-limit
   #:slider-constraint/get-lower-lin-limit
   #:slider-constraint/get-max-ang-motor-force
   #:slider-constraint/get-max-lin-motor-force
   #:slider-constraint/get-powered-ang-motor
   #:slider-constraint/get-powered-lin-motor
   #:slider-constraint/get-restitution-dir-ang
   #:slider-constraint/get-restitution-dir-lin
   #:slider-constraint/get-restitution-lim-ang
   #:slider-constraint/get-restitution-lim-lin
   #:slider-constraint/get-restitution-ortho-ang
   #:slider-constraint/get-restitution-ortho-lin
   #:slider-constraint/get-rigid-body-a
   #:slider-constraint/get-rigid-body-b
   #:slider-constraint/get-softness-dir-ang
   #:slider-constraint/get-softness-dir-lin
   #:slider-constraint/get-softness-lim-ang
   #:slider-constraint/get-softness-lim-lin
   #:slider-constraint/get-softness-ortho-ang
   #:slider-constraint/get-softness-ortho-lin
   #:slider-constraint/get-solve-ang-limit
   #:slider-constraint/get-solve-lin-limit
   #:slider-constraint/get-target-ang-motor-velocity
   #:slider-constraint/get-target-lin-motor-velocity
   #:slider-constraint/get-upper-ang-limit
   #:slider-constraint/get-upper-lin-limit
   #:slider-constraint/get-use-frame-offset
   #:slider-constraint/get-use-linear-reference-frame-a
   #:slider-constraint/make-c++-array
   #:slider-constraint/make-c++-instance
   #:slider-constraint/serialize
   #:slider-constraint/set-damping-dir-ang
   #:slider-constraint/set-damping-dir-lin
   #:slider-constraint/set-damping-lim-ang
   #:slider-constraint/set-damping-lim-lin
   #:slider-constraint/set-damping-ortho-ang
   #:slider-constraint/set-damping-ortho-lin
   #:slider-constraint/set-frames
   #:slider-constraint/set-lower-ang-limit
   #:slider-constraint/set-lower-lin-limit
   #:slider-constraint/set-max-ang-motor-force
   #:slider-constraint/set-max-lin-motor-force
   #:slider-constraint/set-powered-ang-motor
   #:slider-constraint/set-powered-lin-motor
   #:slider-constraint/set-restitution-dir-ang
   #:slider-constraint/set-restitution-dir-lin
   #:slider-constraint/set-restitution-lim-ang
   #:slider-constraint/set-restitution-lim-lin
   #:slider-constraint/set-restitution-ortho-ang
   #:slider-constraint/set-restitution-ortho-lin
   #:slider-constraint/set-softness-dir-ang
   #:slider-constraint/set-softness-dir-lin
   #:slider-constraint/set-softness-lim-ang
   #:slider-constraint/set-softness-lim-lin
   #:slider-constraint/set-softness-ortho-ang
   #:slider-constraint/set-softness-ortho-lin
   #:slider-constraint/set-target-ang-motor-velocity
   #:slider-constraint/set-target-lin-motor-velocity
   #:slider-constraint/set-upper-ang-limit
   #:slider-constraint/set-upper-lin-limit
   #:slider-constraint/set-use-frame-offset
   #:slider-constraint/test-ang-limits
   #:slider-constraint/test-lin-limits
   #:slider-flags
   #:slider-flags
   #:sphere-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:sphere-shape/calculate-local-inertia
   #:sphere-shape/delete-c++-array
   #:sphere-shape/delete-c++-instance
   #:sphere-shape/get-aabb
   #:sphere-shape/get-margin
   #:sphere-shape/get-name
   #:sphere-shape/get-radius
   #:sphere-shape/local-get-supporting-vertex
   #:sphere-shape/local-get-supporting-vertex-without-margin
   #:sphere-shape/make-c++-array
   #:sphere-shape/make-c++-instance
   #:sphere-shape/set-margin
   #:sphere-shape/set-unscaled-radius
   #:sphere-sphere-collision-algorithm/calculate-time-of-impact
   #:sphere-sphere-collision-algorithm/get-all-contact-manifolds
   #:sphere-sphere-collision-algorithm/process-collision
   #:spring-damping
   #:spring-enabled
   #:spring-stiffness
   #:square-root
   #:stage
   #:stage-current
   #:stage-roots
   #:start-world-trans
   #:static-object-p
   #:static-or-kinematic-object-p
   #:static-plane-shape-data
   #:static-plane-shape/calculate-local-inertia
   #:static-plane-shape/calculate-serialize-buffer-size
   #:static-plane-shape/delete-c++-array
   #:static-plane-shape/delete-c++-instance
   #:static-plane-shape/get-aabb
   #:static-plane-shape/get-local-scaling
   #:static-plane-shape/get-name
   #:static-plane-shape/get-plane-constant
   #:static-plane-shape/get-plane-normal
   #:static-plane-shape/make-c++-array
   #:static-plane-shape/make-c++-instance
   #:static-plane-shape/process-all-triangles
   #:static-plane-shape/serialize
   #:static-plane-shape/set-local-scaling
   #:step-simulation
   #:str-len
   #:swap-endian
   #:swap-endian-double
   #:swap-endian-float
   #:swap-scalar-endian
   #:swap-vector-3-endian
   #:swing-span-1
   #:swing-span-2
   #:synchronize-all-motion-states
   #:synchronize-motion-states
   #:synchronize-single-motion-state
   #:tangent
   #:tau
   #:total-force
   #:total-torque
   #:transform
   #:transform-double-data
   #:transform-float-data
   #:transform///funcall//
   #:transform/assign-value
   #:transform/de-serialize
   #:transform/de-serialize-double
   #:transform/de-serialize-float
   #:transform/get-basis
   #:transform/get-identity
   #:transform/get-open-glmatrix
   #:transform/get-origin
   #:transform/get-rotation
   #:transform/inv-xform
   #:transform/inverse
   #:transform/inverse-times
   #:transform/mult
   #:transform/multiply
   #:transform/multiply-and-assign
   #:transform/serialize
   #:transform/serialize-float
   #:transform/set-basis
   #:transform/set-from-open-glmatrix
   #:transform/set-identity
   #:transform/set-origin
   #:transform/set-rotation
   #:translational-limit-motor/is-limited
   #:translational-limit-motor/m/accumulated-impulse/get
   #:translational-limit-motor/m/accumulated-impulse/set
   #:translational-limit-motor/m/current-limit-error/get
   #:translational-limit-motor/m/current-limit-error/set
   #:translational-limit-motor/m/current-limit/get
   #:translational-limit-motor/m/current-limit/set
   #:translational-limit-motor/m/current-linear-diff/get
   #:translational-limit-motor/m/current-linear-diff/set
   #:translational-limit-motor/m/damping/get
   #:translational-limit-motor/m/damping/set
   #:translational-limit-motor/m/enable-motor/get
   #:translational-limit-motor/m/enable-motor/set
   #:translational-limit-motor/m/limit-softness/get
   #:translational-limit-motor/m/limit-softness/set
   #:translational-limit-motor/m/lower-limit/get
   #:translational-limit-motor/m/lower-limit/set
   #:translational-limit-motor/m/max-motor-force/get
   #:translational-limit-motor/m/max-motor-force/set
   #:translational-limit-motor/m/normal-cfm/get
   #:translational-limit-motor/m/normal-cfm/set
   #:translational-limit-motor/m/restitution/get
   #:translational-limit-motor/m/restitution/set
   #:translational-limit-motor/m/stop-cfm/get
   #:translational-limit-motor/m/stop-cfm/set
   #:translational-limit-motor/m/stop-erp/get
   #:translational-limit-motor/m/stop-erp/set
   #:translational-limit-motor/m/target-velocity/get
   #:translational-limit-motor/m/target-velocity/set
   #:translational-limit-motor/m/upper-limit/get
   #:translational-limit-motor/m/upper-limit/set
   #:translational-limit-motor/need-apply-force
   #:translational-limit-motor/solve-linear-axis
   #:translational-limit-motor/test-limit-value
   #:triangle-index
   #:triangle-index-base
   #:triangle-index-stride
   #:triangle-index-vertex-array/add-indexed-mesh
   #:triangle-index-vertex-array/delete-c++-array
   #:triangle-index-vertex-array/delete-c++-instance
   #:triangle-index-vertex-array/get-indexed-mesh-array
   #:triangle-index-vertex-array/get-locked-read-only-vertex-index-base
   #:triangle-index-vertex-array/get-locked-vertex-index-base
   #:triangle-index-vertex-array/get-num-sub-parts
   #:triangle-index-vertex-array/get-premade-aabb
   #:triangle-index-vertex-array/has-premade-aabb
   #:triangle-index-vertex-array/make-c++-array
   #:triangle-index-vertex-array/make-c++-instance
   #:triangle-index-vertex-array/preallocate-indices
   #:triangle-index-vertex-array/preallocate-vertices
   #:triangle-index-vertex-array/set-premade-aabb
   #:triangle-index-vertex-array/un-lock-read-only-vertex-base
   #:triangle-index-vertex-array/un-lock-vertex-base
   #:triangle-info-map
   #:triangle-mesh-shape-data
   #:triangle-mesh-shape/calculate-local-inertia
   #:triangle-mesh-shape/delete-c++-array
   #:triangle-mesh-shape/delete-c++-instance
   #:triangle-mesh-shape/get-aabb
   #:triangle-mesh-shape/get-local-aabb-max
   #:triangle-mesh-shape/get-local-aabb-min
   #:triangle-mesh-shape/get-local-scaling
   #:triangle-mesh-shape/get-mesh-interface
   #:triangle-mesh-shape/get-name
   #:triangle-mesh-shape/local-get-supporting-vertex
   #:triangle-mesh-shape/local-get-supporting-vertex-without-margin
   #:triangle-mesh-shape/make-c++-array
   #:triangle-mesh-shape/make-c++-instance
   #:triangle-mesh-shape/process-all-triangles
   #:triangle-mesh-shape/recalc-local-aabb
   #:triangle-mesh-shape/set-local-scaling
   #:triangle-mesh/add-index
   #:triangle-mesh/add-triangle
   #:triangle-mesh/find-or-add-vertex
   #:triangle-mesh/get-num-triangles
   #:triangle-mesh/get-use-32bit-indices
   #:triangle-mesh/get-use-4component-vertices
   #:triangle-mesh/m/welding-threshold/get
   #:triangle-mesh/m/welding-threshold/set
   #:triangle-mesh/preallocate-indices
   #:triangle-mesh/preallocate-vertices
   #:trimesh-shape-data
   #:triple
   #:twist-span
   #:type-constraint-data
   #:typed-constraint-data
   #:typed-constraint-double-data
   #:typed-constraint-float-data
   #:typed-constraint-type
   #:typed-constraint/build-jacobian
   #:typed-constraint/calculate-serialize-buffer-size
   #:typed-constraint/delete-c++-array
   #:typed-constraint/delete-c++-instance
   #:typed-constraint/enable-feedback
   #:typed-constraint/get-applied-impulse
   #:typed-constraint/get-breaking-impulse-threshold
   #:typed-constraint/get-constraint-type
   #:typed-constraint/get-dbg-draw-size
   #:typed-constraint/get-fixed-body
   #:typed-constraint/get-info-1
   #:typed-constraint/get-info-2
   #:typed-constraint/get-joint-feedback
   #:typed-constraint/get-override-num-solver-iterations
   #:typed-constraint/get-rigid-body-a
   #:typed-constraint/get-rigid-body-b
   #:typed-constraint/get-uid
   #:typed-constraint/get-user-constraint-id
   #:typed-constraint/get-user-constraint-ptr
   #:typed-constraint/get-user-constraint-type
   #:typed-constraint/internal-get-applied-impulse
   #:typed-constraint/internal-set-applied-impulse
   #:typed-constraint/is-enabled
   #:typed-constraint/make-c++-array
   #:typed-constraint/make-c++-instance
   #:typed-constraint/needs-feedback
   #:typed-constraint/serialize
   #:typed-constraint/set-breaking-impulse-threshold
   #:typed-constraint/set-dbg-draw-size
   #:typed-constraint/set-enabled
   #:typed-constraint/set-joint-feedback
   #:typed-constraint/set-override-num-solver-iterations
   #:typed-constraint/set-user-constraint-id
   #:typed-constraint/set-user-constraint-ptr
   #:typed-constraint/set-user-constraint-type
   #:typed-constraint/setup-solver-constraint
   #:typed-constraint/solve-constraint-obsolete
   #:typed-object
   #:un-swap-vector-3-endian
   #:uniform-scaling-shape/batched-unit-vector-get-supporting-vertex-without-margin
   #:uniform-scaling-shape/calculate-local-inertia
   #:uniform-scaling-shape/delete-c++-array
   #:uniform-scaling-shape/delete-c++-instance
   #:uniform-scaling-shape/get-aabb
   #:uniform-scaling-shape/get-aabb-slow
   #:uniform-scaling-shape/get-child-shape
   #:uniform-scaling-shape/get-local-scaling
   #:uniform-scaling-shape/get-margin
   #:uniform-scaling-shape/get-name
   #:uniform-scaling-shape/get-num-preferred-penetration-directions
   #:uniform-scaling-shape/get-preferred-penetration-direction
   #:uniform-scaling-shape/get-uniform-scaling-factor
   #:uniform-scaling-shape/local-get-supporting-vertex
   #:uniform-scaling-shape/local-get-supporting-vertex-without-margin
   #:uniform-scaling-shape/make-c++-array
   #:uniform-scaling-shape/make-c++-instance
   #:uniform-scaling-shape/set-local-scaling
   #:uniform-scaling-shape/set-margin
   #:universal-constraint/delete-c++-array
   #:universal-constraint/delete-c++-instance
   #:universal-constraint/get-anchor
   #:universal-constraint/get-anchor-2
   #:universal-constraint/get-angle-1
   #:universal-constraint/get-angle-2
   #:universal-constraint/get-axis-1
   #:universal-constraint/get-axis-2
   #:universal-constraint/make-c++-array
   #:universal-constraint/make-c++-instance
   #:universal-constraint/set-axis
   #:universal-constraint/set-lower-limit
   #:universal-constraint/set-upper-limit
   #:unscaled-points-double-ptr
   #:unscaled-points-float-ptr
   #:unswap-endian-double
   #:unswap-endian-float
   #:up-axis
   #:up-index
   #:update-aabbs
   #:update-revision-internal
   #:update-single-aabb
   #:update-vehicles
   #:updates-call
   #:updates-done
   #:updates-ratio
   #:upper-limit
   #:use-epa-penetration-algorithm
   #:use-linear-reference-frame-a
   #:use-offset-for-constraint-frame
   #:use-reference-frame-a
   #:user-constraint-id
   #:user-constraint-type
   #:user-index
   #:user-pointer
   #:user-pointer
   #:vector-3-double-data
   #:vector-3-float-data
   #:vector-3/absolute
   #:vector-3/angle
   #:vector-3/closest-axis
   #:vector-3/cross
   #:vector-3/de-serialize
   #:vector-3/de-serialize-double
   #:vector-3/de-serialize-float
   #:vector-3/decrement
   #:vector-3/delete-c++-array
   #:vector-3/delete-c++-instance
   #:vector-3/distance
   #:vector-3/distance-2
   #:vector-3/divide-and-assign
   #:vector-3/dot
   #:vector-3/dot-3
   #:vector-3/furthest-axis
   #:vector-3/fuzzy-zero
   #:vector-3/get-skew-symmetric-matrix
   #:vector-3/get-x
   #:vector-3/get-y
   #:vector-3/get-z
   #:vector-3/increment
   #:vector-3/is-equal
   #:vector-3/is-zero
   #:vector-3/length
   #:vector-3/length-2
   #:vector-3/m/floats/get
   #:vector-3/m/floats/set
   #:vector-3/make-c++-array
   #:vector-3/make-c++-instance
   #:vector-3/max-axis
   #:vector-3/max-dot
   #:vector-3/min-axis
   #:vector-3/min-dot
   #:vector-3/multiply-and-assign
   #:vector-3/norm
   #:vector-3/normalize
   #:vector-3/normalized
   #:vector-3/not-equals
   #:vector-3/rotate
   #:vector-3/safe-normalize
   #:vector-3/serialize
   #:vector-3/serialize-double
   #:vector-3/serialize-float
   #:vector-3/set-interpolate-3
   #:vector-3/set-max
   #:vector-3/set-min
   #:vector-3/set-value
   #:vector-3/set-w
   #:vector-3/set-x
   #:vector-3/set-y
   #:vector-3/set-z
   #:vector-3/set-zero
   #:vector-3/triple
   #:vector-3/w
   #:vector-3/x
   #:vector-3/y
   #:vector-3/z
   #:vector-4/absolute-4
   #:vector-4/closest-axis-4
   #:vector-4/get-w
   #:vector-4/max-axis-4
   #:vector-4/min-axis-4
   #:vector-4/set-value
   #:vector/angle
   #:vector3/dot
   #:vector3/vlerp
   #:vertex-base
   #:vertex-stride
   #:vertex-type
   #:vlerp
   #:world-transform
   #:world-transform
   #:world-type
   #:+active-tag+
   #:*deactivation-time*
   ))

(in-package #:bullet-physics)

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (defun lispify (identifier expression &optional (package cl:*package*)
                  &aux (setf% nil))
    (check-type identifier string)
    (assert (member expression '(function method
                                 classname class enumname
                                 constant enumvalue
                                 variable slotname)))
    
    (when (and (> (length identifier) 4)
               (or (equal (subseq identifier 0 4) "set-")
                   (equal (subseq identifier 0 4) "set_"))
               (eql expression 'method))
      (setf identifier (subseq identifier 4)
            setf% t))
    (when (and (> (length identifier) 4)
               (or (equal (subseq identifier 0 4) "get-")
                   (equal (subseq identifier 0 4) "get_")))
      (setf identifier (subseq identifier 4)))
    (when (and (> (length identifier) 3)
               (or (equal (subseq identifier 0 3) "is-")
                   (equal (subseq identifier 0 3) "is_")))
      (setf identifier (concatenate
                        'string (subseq identifier 3) 
                        (if (or (find #\- (subseq identifier 3))
                                (find #\_ (subseq identifier 3)))
                            "-p" "p"))))
    (when (and (> (length identifier) 4)
               (or (equal (subseq identifier 0 4) "has-")
                   (equal (subseq identifier 0 4) "has_")))
      (setf identifier (concatenate 'string identifier "-p")))
    (when (and (> (length identifier) 4)
               (equal (subseq identifier 0 4) "new_")
               (member expression '(function method)))
      (setf identifier (concatenate
                        'string "make-"
                        (cond ((or (equal (subseq identifier 4 7) "bt_")
                                   (equal (subseq identifier 4 7) "BT_")
                                   (equal (subseq identifier 4 7) "bt-"))
                               (subseq identifier 7))
                              ((equal (subseq identifier 4 6) "bt")
                               (subseq identifier 6))
                              (t (subseq identifier 4))))))

    (when (and (eql expression 'variable)
               (eql (elt identifier 0) #\g))
      (setf identifier (subseq identifier 1)))
    (when (and (> (length identifier) 3)
               (or (equal (subseq identifier 0 2) "m_")
                   (equal (subseq identifier 0 2) "m-")))
      (setf identifier (subseq identifier 2)))
    (when (and (> (length identifier) 3)
               (or (equal (subseq identifier 0 3) "bt_")
                   (equal (subseq identifier 0 3) "BT_")
                   (equal (subseq identifier 0 3) "bt-")))
      (setf identifier (subseq identifier 3)))
    (when (and (> (length identifier) 2)
               (equal (subseq identifier 0 2) "bt"))
      (setf identifier (subseq identifier 2)))

    (let ((name identifier)
          (flag expression))
      (labels
          ((helper (list last rest &aux (c (car list)))
             (cond
               ((null list) rest)
               ((upper-case-p c)    (helper (cdr list) 'upper
                                            (case last
                                              ((lower
                                                digit)  (list* c #\- rest))
                                              (t        (cons c rest)))))
               ((lower-case-p c)    (helper (cdr list) 'lower
                                            (cons (char-upcase c) rest)))
               ((digit-char-p c)    (helper (cdr list) 'digit
                                            (case last
                                              ((upper
                                                lower)  (list* c #\- rest))
                                              (t        (cons c rest)))))

               ((char-equal c #\_)  (helper (cdr list) '_
                                            (cons (case expression 
                                                    ((method 
                                                      function
                                                      classname
                                                      class
                                                      enumname) #\/)
                                                    (otherwise #\-)) rest)))
               (t                   (helper (cdr list) '_
                                            (cons c rest))))))
        
        (let ((fix (case flag
                     (constant "+")
                     (variable "*")
                     (otherwise ""))))
          (let ((token (concatenate 'string
                                    fix
                                    (nreverse (helper (concatenate 'list name)
                                                      nil nil))
                                    fix)))
            (when-let ((sym (find-symbol token :common-lisp)))
              (when (case flag
                      ((function method slotname)     (fboundp sym))
                      ((variable constant enumvalue)  (boundp sym))))
              (setf token (concatenate 'string "BULLET/" token)))
            (let ((sym (intern token package)))
              
              (if setf%
                  (list 'setf sym)
                  sym))))))))

(defmacro defmeth (name &rest method-stuff)
  `(progn (defmethod ,name ,@method-stuff)
          (export ',name)))

(defmacro defklass (name &rest method-stuff)
  `(progn (defclass ,name ,@method-stuff)
          (export ',name)))

(defmacro define-anonymous-enum (&body enums)
  "Converts anonymous enums to defconstants."
  `(progn ,@(loop for value in enums
               for index = 0 then (1+ index)
               when (listp value) do (setf index (second value)
                                           value (first value))
               collect `(define-constant ,value ,index))))


