#!/bin/bash
wget https://s3.amazonaws.com/conceptnet/precomputed-data/2016/assertions/conceptnet-assertions-5.5.0.csv.gz
gzip -dc < conceptnet-assertions-5.5.0.csv.gz > conceptnet-assertions-5.5.0.csv
