CREATE TABLE userHouseRooms (
userID INT NOT NULL, 
roomID DECIMAL(1,0) UNSIGNED NOT NULL, 
PRIMARY KEY (userID, roomID), 
CONSTRAINT FOREIGN KEY (userID) REFERENCES users (ID)
) ENGINE=InnoDB;

CREATE TABLE itemCollections (
ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(32) NOT NULL UNIQUE KEY,
onBreak INT NULL,
CONSTRAINT FOREIGN KEY (onBreak) REFERENCES eventTypes (ID),
onComplete INT NULL,
CONSTRAINT FOREIGN KEY (onComplete) REFERENCES eventTypes (ID)
) ENGINE=InnoDB;

CREATE TABLE eventOutcomes (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
giveMedal INT NULL,
CONSTRAINT FOREIGN KEY (giveMedal) REFERENCES medalTypes(ID),
maxRarity TINYINT NOT NULL DEFAULT 4,
minRarity TINYINT NOT NULL DEFAULT 1,
CONSTRAINT FOREIGN KEY (maxRarity) REFERENCES itemRarities(ID),
CONSTRAINT FOREIGN KEY (minRarity) REFERENCES itemRarities(ID),
onDupe ENUM ('R','I','N') NOT NULL DEFAULT 'I',
rewardPoints ENUM ('Y','N') NOT NULL DEFAULT 'Y',
rewardCurrency CHAR(3) NOT NULL DEFAULT 'xTP',
rewardCollectionID INT UNSIGNED NULL,
CONSTRAINT FOREIGN KEY (rewardCollectionID) REFERENCES itemCollections(ID),
rewardItemID INT NULL,
CONSTRAINT FOREIGN KEY (rewardItemID) REFERENCES items (ID),
rewardRatio DECIMAL(10,5) NOT NULL DEFAULT 00001.00000,
  rewardRandom ENUM ('Y','N') NOT NULL DEFAULT 'N',
  rewardMin DECIMAL(5,0) NOT NULL DEFAULT -99999,
  rewardMax DECIMAL(5,0) NOT NULL DEFAULT 99999,
rewardInventoryItemType ENUM('I','C','G','N') NOT NULL DEFAULT 'N'
) ENGINE=InnoDB;

ALTER TABLE users ADD COLUMN travelRate DECIMAL(5,2) UNSIGNED NOT NULL DEFAULT 100.00;
ALTER TABLE users ADD COLUMN parentApprovedName ENUM('Y','N') NOT NULL DEFAULT 'N';
ALTER TABLE users ADD COLUMN lastZoneName VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE events CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE eventTypes CHANGE COLUMN outcome outcome INT NOT NULL DEFAULT 3;
ALTER TABLE eventTypes ADD CONSTRAINT FOREIGN KEY (outcome) REFERENCES eventOutcomes (ID);
ALTER TABLE eventTypes CHANGE COLUMN filename filename VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE eventTypes CHANGE COLUMN description description TEXT NOT NULL;
ALTER TABLE eventTypes ADD COLUMN frequencyLimit DECIMAL(2,0) UNSIGNED NOT NULL DEFAULT 99;
ALTER TABLE eventTypes ADD COLUMN frequencyPeriod DECIMAL(6,0) UNSIGNED NOT NULL DEFAULT 1;
ALTER TABLE inventory ADD COLUMN z INT NULL;
ALTER TABLE inventory ADD COLUMN name VARCHAR(20) NULL;
ALTER TABLE inventory ADD CONSTRAINT UNIQUE KEY (userID, name);
ALTER TABLE inventory ADD COLUMN health DECIMAL(4,1) NOT NULL DEFAULT 100.0;
ALTER TABLE inventory ADD COLUMN container ENUM ('R','U','I','C') NOT NULL DEFAULT 'U';

