{document.writeln("<script type=\"text/javascript\">");
document.writeln("var udmsid = 7136;");
document.writeln("var udmcb = (Math.random() * 99999999);");
document.writeln("<\/script>");
document.writeln("");
document.writeln("<!-- BEGIN JS TAG - Underdog Media Ent 300x250 < - DO NOT MODIFY -->");
document.writeln("<SCRIPT SRC=\"http://ib.adnxs.com/ttj?id=1812775&cb=143160&referrer=http%3A%2F%2Fdeviantart.com\" TYPE=\"text/javascript\"><\/script>");
document.writeln("<!-- END TAG --><!-- MID 27241 -->");
document.writeln("<!-- Start Quantcast tag -->");
document.writeln("        <script type=\"text/javascript\">");
document.writeln("        _qoptions={");
document.writeln("        qacct:\"p-effSsmMYCbAck\",");
document.writeln("        labels:\"cat.11,sid.7136\"");
document.writeln("        };");
document.writeln("        <\/script>");
document.writeln("        <script type=\"text/javascript\" src=\"http://edge.quantserve.com/quant.js\"><\/script>");
document.writeln("        <noscript>");
document.writeln("        <img src=\"http://pixel.quantserve.com/pixel/p-effSsmMYCbAck.gif\" style=\"display: none;\" border=\"0\" height=\"1\" width=\"1\" alt=\"Quantcast\"/>");
document.writeln("        </noscript>");
document.writeln("        <!-- udm25 End Quantcast tag --> <div style=\"display:inline;\"><img height=\"1\" width=\"1\" style=\"border-style:none;\" alt=\"\" src=\"//googleads.g.doubleclick.net/pagead/viewthroughconversion/1022259080/?value=0&amp;label=9BgXCNCQqQQQiN-55wM&amp;guid=ON&amp;script=0\"/><\/div> ");}