#!/bin/bash
for set in texai-lexicon-rdf wiktionary-rdf wordnet-rdf cmu-pronouncing-dictionary-rdf open-cyc-rdf
do
  curl https://sourceforge.net/projects/texai/files/$set/1.1/ \
  | grep download_url \
  | sed -e 's/,/\n/g' \
  | grep download_url \
  | cut -d: -f2- \
  | cut -d '"' -f2 \
  | while read uri
    do
      wget -c $uri -O $(echo $uri | cut -d/ -f9)
    done
done
