#!/bin/bash
curl http://rtw.ml.cmu.edu/resources/results/08m/ \
  | grep href \
  | perl -ne 'print "http://rtw.ml.cmu.edu/resources/results/08m/$1\n" if m[href="(NELL.*(sv|sv.gz))"]' \
  | sort \
  | uniq \
  | parallel --will-cite -P2 --progress --bar wget -c
