#!/bin/sh

if [ "$1x" = "x" ] 
then
    echo "Usage: $0 SWFDIR" >&2
    exit -2
fi

export SWFDIR=$1

find $SWFDIR -type f -name \*.swf -print0 | \
    perl -0 -e '
   while (my $swf = <>)
    { chomp $swf;
      $swf =~ s, ,\\ ,g;
      my $collada = $swf;
      $collada =~ s,\Q$ENV{SWFDIR}\E/*,build/art/,g; 
      $collada =~ s,\.swf$,\.min\.collada,;
      print "$svg:\t\\\n\t\t$swf\n\n$collada:\t\\\n\t\t$swf\n\n" }'

#find $SWFDIR -type f -name \*.ttf -o -name \*.mp3 -print0 | \
#    perl -0 -e 'while (my $src = <>) { chomp $src;
#  my $dest = $src; $dest =~ s,\Q$ENV{SWFDIR}\E/*,build/assets.bin/,g; 
#  print "$dest:\t\\\n\t\t$src\n\n" }' \
#    > assets.mak

find $SWFDIR -type d -print0 | \
     perl -0 -e 'while (my $d = <>) { chomp $d; $d =~ s,\Q$ENV{SWFDIR}\E/*,build/art/,g; mkdir $d }'

echo -e '\n\n\n'

echo 'VERSIONEDASSETS=\'

find $SWFDIR -type f -name \*.swf -print0 | \
    perl -0 -e '
   while (my $swf = <>)
    { chomp $swf;
      $swf =~ s, ,\\ ,g;
      my $collada = $swf;
      $collada =~ s,\.swf$,\.svg,;
      $collada =~ s,\Q$ENV{SWFDIR}\E/*,build/\$(PROJECT)-assets/,g; 
      print "\t $collada \\\n" }'



