#!/bin/bash
wget -rm http://downloads.dbpedia.org/2016-04/links/ &
wget -rm http://downloads.dbpedia.org/2016-04/core-i18n/en/ &
wget -rm http://downloads.dbpedia.org/2016-04/core-i18n/ &
fg %1
fg %2
fg %3
