#!/bin/bash

if ! which parallel
then
  echo "Need to install GNU Parallel" >&2
  pkcon install parallel || sudo dnf -y install parallel
fi

timeout 10 parallel --bibtex --will-cite < /dev/null

# Run WGet in parallel; use up to half the number of CPU cores for this. 
# Abort whenever 2 jobs have failed.

exec parallel --will-cite --halt now,fail=2 -P50% wget -q -c -r -m -np <<END
http://downloads.dbpedia.org/2016-04/
http://downloads.dbpedia.org/2016-04/core/
http://downloads.dbpedia.org/2016-04/ext/
http://downloads.dbpedia.org/2016-04/links/
http://downloads.dbpedia.org/2016-04/statistics/
http://downloads.dbpedia.org/2016-04/core-i18n/en/
http://downloads.dbpedia.org/2016-04/core-i18n/es/
http://downloads.dbpedia.org/2016-04/core-i18n/fr/
http://downloads.dbpedia.org/2016-04/core-i18n/de/
END

