#!/bin/bash
until ./check-checksums
do
    echo "So far, downloaded:"
    du -sh downloads.dbpedia.org
    echo "Available space on volume:"
    df -h .
    echo ""
    echo "One or more files have not downloaded properly." >&2
    echo "Are the download processes are still running …?"
    if pgrep -af wget | grep dbpedia
    then
        echo "They are; let's sleep a couple minutes before checking again."
        sleep 200
    else
        echo "It seems that they have stopped, so we'll just fetch any missing bits."
        ./grab-missing
    fi
done
echo "All seems well. Done."
exit 0
