#!/bin/bash
until ./check-checksums
do
  echo "One or more files have not downloaded properly." >&2
  echo "Assuming that the download processes are still running …"
  if ! pgrep -af wget | grep dbpedia
  then
    echo "It seems that they have stopped. Let's restart them."
    ./download-dbpedia &
    sleep 3
    if ! pgrep -af wget | grep dbpedia
    then
      echo "Downloads are not running; aborting" >&2
      exit 4
    fi
  fi
  echo "Downloads are running, so we'll wait a few minutes and try again."
  echo "So far, downloaded:"
  du -sh downloads.dbpedia.org
  date
  echo ""
  sleep 275
  date
done
echo "All seems well. Done."
exit 0
